spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
            google:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}

logging:
  file:
    name: app.log
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  level:
    root: warn
    io:
      github:
        cristian_eds: trace
    org:
      springframework:
        web: debug

springdoc:
  override-with-generic-response: false

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
